version: '3.2'
services:
  sonarqube:
    build:
      context: sonarqube/
    privileged: true
    container_name: sonarqube
    environment: 
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - VIRTUAL_HOST=sonarqube.owens-netsec.com
      - LETSENCRYPT_HOST=sonarqube.owens-netsec.com
      - LETSENCRYPT_EMAIL=simonowens157@gmail.com
      - VIRTUAL_PORT=9000
    volumes:
      - /docker/data/sonarqube/sonarqube_conf:/opt/sonarqube/conf
      - /docker/data/sonarqube/sonarqube_data:/opt/sonarqube/data
      - /docker/data/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - /docker/data/sonarqube/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  
  db:
    image: postgres
    build: /docker/postgres/
    privileged: true
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /docker/data/postgres/postgresql:/var/lib/postgresql
      - /docker/data/postgres/postgresql_data:/var/lib/postgresql/data

  jenkins:
    build:
      context: jenkins/
    privileged: true
    user: root
    container_name: jenkins
    environment: 
      - VIRTUAL_HOST=jenkins.owens-netsec.com
      - LETSENCRYPT_HOST=jenkins.owens-netsec.com
      - LETSENCRYPT_EMAIL=simonowens157@gmail.com
      - VIRTUAL_PORT=8080
    volumes:
      - /docker/data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - sonarqube

networks:
  default:
    external:
      name: webproxy
