version: '3.1'

services:
  db:
    restart: always
    image: postgres
    build: /docker/postgres/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres_pass 
    volumes:
      - /data/django/:/data/web
  web:
    restart: always
    build: .
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db

secrets:
  postgres_pass:
        file: /data/django/postgres.txt
